# Generated by Django 5.0.6 on 2024-06-10 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PawfetchMatch_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
