# Generated by Django 5.0.6 on 2024-06-17 15:31

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PawfetchMatch_app', '0008_listing_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='username',
            field=models.CharField(default=django.contrib.auth.models.User, max_length=50),
        ),
    ]
