# Generated by Django 5.0.6 on 2024-06-17 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PawfetchMatch_app', '0009_alter_listing_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='username',
        ),
    ]
